# Generated by Django 4.0.3 on 2023-12-17 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0002_remove_language_client_remove_occupation_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepicture',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_picture', to='Client.client'),
        ),
    ]
