# Generated by Django 4.0.3 on 2023-11-28 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='occupation',
            name='seller',
        ),
        migrations.AlterField(
            model_name='education',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='Seller.seller'),
        ),
        migrations.AlterField(
            model_name='language',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language', to='Seller.seller'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='Seller.seller'),
        ),
        migrations.DeleteModel(
            name='Certification',
        ),
        migrations.DeleteModel(
            name='Occupation',
        ),
    ]
