# Generated by Django 4.0.3 on 2023-11-29 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0003_alter_education_seller_alter_language_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepicture',
            name='seller',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_picture', to='Seller.seller'),
        ),
    ]
