# Generated by Django 4.0.3 on 2023-11-28 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Client', '0001_initial'),
        ('Seller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(choices=[('short', 'Short Term'), ('long', 'Long Term')], max_length=10)),
                ('job_title', models.TextField()),
                ('scope', models.CharField(choices=[('large', 'Large'), ('medium', 'Medium'), ('small', 'Small')], max_length=10)),
                ('length', models.CharField(choices=[('3-6', '3 to 6 months'), ('1-3', '1 to 3 months'), ('<1', 'Less than 1 month')], max_length=5)),
                ('experience_needed', models.CharField(choices=[('entry', 'Entry'), ('intermediate', 'Intermediate'), ('expert', 'Expert')], max_length=15)),
                ('hire_opp', models.BooleanField()),
                ('project_budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='attachments/')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Client.client')),
                ('freelancer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Seller.seller')),
                ('skills', models.ManyToManyField(to='jobpost.skill')),
            ],
        ),
    ]
