# Generated by Django 4.0.3 on 2023-11-28 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0001_initial'),
        ('jobpost', '0002_savedjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedjob',
            name='job_post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='jobpost.jobpost'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='savedjob',
            name='seller',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Seller.seller'),
            preserve_default=False,
        ),
    ]
