# Generated by Django 4.0.3 on 2023-11-28 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobpost', '0001_initial'),
        ('Seller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration', models.CharField(choices=[('more_than_6m', 'More than 6 months'), ('3m_to_6m', '3 to 6 months'), ('1m_to_3m', '1 to 3 months'), ('less_than_1m', 'Less than 1 month')], max_length=20)),
                ('cover_letter', models.TextField()),
                ('relevant_examples', models.TextField()),
                ('attachments', models.FileField(upload_to='JOBProposal')),
                ('job_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='jobpost.jobpost')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seller.seller')),
            ],
        ),
    ]
